### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by LucasB25** [appujet/lavamusic#533]
```
[09/04/2024] [23:13:17] [antiCrash.js] [Lavamusic] › ✖  error     Unhandled Rejection at: Promise {
  <rejected> TypeError: Cannot read properties of undefined (reading 'channelId')
      at Timeout._onTimeout (file:///home/pi/MusicBot/LucasB25/PanaisV2/dist/events/client/VoiceStateUpdate.js:52:136)
      at listOnTimeout (node:internal/timers:573:17)
      at process.processTimers (node:internal/timers:514:7)
} reason: TypeError: Cannot read properties of undefined (reading 'channelId')
    at Timeout._onTimeout (file:///home/pi/MusicBot/LucasB25/PanaisV2/dist/events/client/VoiceStateUpdate.js:52:136)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
```

**Comment by pheeef** [comment]
Having zero information about this makes it hard to reproduce or even diagnose. My first guess would be that bot is not allowed to access the channel in some way.

**Comment by Xenofic** [comment]
@LucasB25 steps to reproduce?

**Comment by LucasB25** [comment]
it’s just a channel to list errors so we can fix them so ignored the
