### ISSUE TITLE
starting causes: undefined:1 (loop)

### ISSUE THREAD

**Issue by godsyn** [appujet/lavamusic#544]
```npm start

> lavamusic@4.1.0 start
> npm run build && node dist/index.js


> lavamusic@4.1.0 build
> tsc --project tsconfig.json


    █░░ ▄▀█ █░█ ▄▀█ █▀▄▀█ █░█ █▀ █ █▀▀
    █▄▄ █▀█ ▀▄▀ █▀█ █░▀░█ █▄█ ▄█ █ █▄▄

             .:::.=++=:.:-:
            =##############*
            *###############.
             =++=*####*=++=:
                 .*##*:
               .+######*:
              =*#########+.
            :*############*-
           =################*.
         :*##################*=
       .+######################*:
       *#########################.
       .::::::::::::::::::::::::.

[4/25/2024] [12:20:09 AM] [index.js] [Lavamusic] › ▶  start     [CLIENT] 1 shard(s) spawned.
undefined:1
<!DOCTYPE html>
^

SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:4292:19)
    at successSteps (node:internal/deps/undici/undici:4274:27)
    at fullyReadBody (node:internal/deps/undici/undici:2695:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async consumeBody (node:internal/deps/undici/undici:4283:7)
    at async Lavamusic.getNodes (file:///opt/lavamusic/dist/structures/Lavamusic.js:123:23)
    at async Lavamusic.start (file:///opt/lavamusic/dist/structures/Lavamusic.js:31:27)

Node.js v21.7.3
undefined:1
<!DOCTYPE html>
^

SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:4292:19)
    at successSteps (node:internal/deps/undici/undici:4274:27)
    at fullyReadBody (node:internal/deps/undici/undici:2695:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async consumeBody (node:internal/deps/undici/undici:4283:7)
    at async Lavamusic.getNodes (file:///opt/lavamusic/dist/structures/Lavamusic.js:123:23)
    at async Lavamusic.start (file:///opt/lavamusic/dist/structures/Lavamusic.js:31:27)

Node.js v21.7.3
```

**Comment by godsyn** [comment]
was a permissions issue. fixed.
