### ISSUE TITLE
Failure to play songs.

### ISSUE THREAD

**Issue by godsyn** [appujet/lavamusic#545]
When I attempt to play a song, I get:

Lavamusic:
```Apr 25 01:12:56 ukulele node[54978]: [4/25/2024] [1:12:56 AM] [SetupSystem.js] [Lavamusic] › ✖  error     TypeError: Cannot read properties of null (reading 'info')
Apr 25 01:12:56 ukulele node[54978]:     at neb (file:///opt/lavamusic-4.1.0/dist/utils/SetupSystem.js:6:54)
Apr 25 01:12:56 ukulele node[54978]:     at setupStart (file:///opt/lavamusic-4.1.0/dist/utils/SetupSystem.js:189:21)
Apr 25 01:12:56 ukulele node[54978]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Apr 25 01:12:56 ukulele node[54978]:     at async SetupSystem.run (file:///opt/lavamusic-4.1.0/dist/events/client/SetupSystem.js:40:9)
```
Lavalink:
```Apr 25 01:12:56 ukulele java[54714]: 2024-04-25T01:12:56.307-04:00  INFO 54714 --- [  XNIO-1 task-2] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "ytsearch:test"
Apr 25 01:12:56 ukulele java[54714]: 2024-04-25T01:12:56.752-04:00  INFO 54714 --- [  XNIO-1 task-2] lavalink.server.player.AudioLoader       : Loaded playlist Search results for: test
Apr 25 01:12:56 ukulele java[54714]: 2024-04-25T01:12:56.754-04:00  INFO 54714 --- [  XNIO-1 task-2] l.server.io.RequestLoggingFilter         : GET /v4/loadtracks?identifier=ytsearch%3Atest, client=127.0.0.1
Apr 25 01:12:56 ukulele java[54714]: 2024-04-25T01:12:56.765-04:00  INFO 54714 --- [  XNIO-1 task-2] l.server.io.RequestLoggingFilter         : PATCH /v4/sessions/3whrbzhtg6pekqm3/players/820872123685535775?noReplace=false, client=127.0.0.1, payload={"encodedTrack":"QAAAuwMAHkkgVGVzdGVkIDEtU3RhciBIb3RlbHMgKGFnYWluKQALUnlhbiBUcmFoYW4AAAAAABtMSAALOFR0NWhoN2dWVncAAQAraHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g/dj04VHQ1aGg3Z1ZWdwEANGh0dHBzOi8vaS55dGltZy5jb20vdmkvOFR0NWhoN2dWVncvbWF4cmVzZGVmYXVsdC5qcGcAAAd5b3V0dWJlAAAAAAAAAAA="}
```

**Comment by LucasB25** [comment]
> When I attempt to play a song, I get:
> 
> Lavamusic:
> 
> ```
> Apr 25 01:12:56 ukulele node[54978]:     at neb (file:///opt/lavamusic-4.1.0/dist/utils/SetupSystem.js:6:54)
> Apr 25 01:12:56 ukulele node[54978]:     at setupStart (file:///opt/lavamusic-4.1.0/dist/utils/SetupSystem.js:189:21)
> Apr 25 01:12:56 ukulele node[54978]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> Apr 25 01:12:56 ukulele node[54978]:     at async SetupSystem.run (file:///opt/lavamusic-4.1.0/dist/events/client/SetupSystem.js:40:9)
> ```
> 
> Lavalink:
> 
> ```
> Apr 25 01:12:56 ukulele java[54714]: 2024-04-25T01:12:56.752-04:00  INFO 54714 --- [  XNIO-1 task-2] lavalink.server.player.AudioLoader       : Loaded playlist Search results for: test
> Apr 25 01:12:56 ukulele java[54714]: 2024-04-25T01:12:56.754-04:00  INFO 54714 --- [  XNIO-1 task-2] l.server.io.RequestLoggingFilter         : GET /v4/loadtracks?identifier=ytsearch%3Atest, client=127.0.0.1
> Apr 25 01:12:56 ukulele java[54714]: 2024-04-25T01:12:56.765-04:00  INFO 54714 --- [  XNIO-1 task-2] l.server.io.RequestLoggingFilter         : PATCH /v4/sessions/3whrbzhtg6pekqm3/players/820872123685535775?noReplace=false, client=127.0.0.1, payload={"encodedTrack":"QAAAuwMAHkkgVGVzdGVkIDEtU3RhciBIb3RlbHMgKGFnYWluKQALUnlhbiBUcmFoYW4AAAAAABtMSAALOFR0NWhoN2dWVncAAQAraHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g/dj04VHQ1aGg3Z1ZWdwEANGh0dHBzOi8vaS55dGltZy5jb20vdmkvOFR0NWhoN2dWVncvbWF4cmVzZGVmYXVsdC5qcGcAAAd5b3V0dWJlAAAAAAAAAAA="}
> ```

https://discord.gg/coders-942117923001098260
https://discord.com/channels/942117923001098260/1232296473673203772
