### ISSUE TITLE
Error with libssl in Docker

### ISSUE THREAD

**Issue by elBelgg** [appujet/lavamusic#573]
I have just updated to 4.3.2 and Im getting this error

**Error code:**
[5/31/2024] [7:10:13 PM] [antiCrash.js] [Lavamusic] › ✖  error     Unhandled Rejection at: Promise {
  <rejected> PrismaClientInitializationError: 
  Invalid `prisma.stay.findMany()` invocation:
  
  
  Unable to require(`/opt/lavamusic/node_modules/.prisma/client/libquery_engine-debian-openssl-1.1.x.so.node`).
  Prisma cannot find the required `libssl` system library in your system. Please install openssl and try again.
  
  Details: libssl.so.1.1: cannot open shared object file: No such file or directory
      at In.handleRequestError (/opt/lavamusic/node_modules/@prisma/client/runtime/library.js:122:7177)
      at In.handleAndLogRequestError (/opt/lavamusic/node_modules/@prisma/client/runtime/library.js:122:6211)
      at In.request (/opt/lavamusic/node_modules/@prisma/client/runtime/library.js:122:5919)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async l (/opt/lavamusic/node_modules/@prisma/client/runtime/library.js:127:11167)
      at async ServerData.get_247 (file:///opt/lavamusic/dist/database/server.js:82:20)
      at async NodeConnect.run (file:///opt/lavamusic/dist/events/player/NodeConnect.js:11:20) {
    clientVersion: '5.14.0',
    errorCode: undefined
  }
} reason: PrismaClientInitializationError: 
Invalid `prisma.stay.findMany()` invocation:

Unable to require(`/opt/lavamusic/node_modules/.prisma/client/libquery_engine-debian-openssl-1.1.x.so.node`).
Prisma cannot find the required `libssl` system library in your system. Please install openssl and try again.

Details: libssl.so.1.1: cannot open shared object file: No such file or directory
    at In.handleRequestError (/opt/lavamusic/node_modules/@prisma/client/runtime/library.js:122:7177)
    at In.handleAndLogRequestError (/opt/lavamusic/node_modules/@prisma/client/runtime/library.js:122:6211)
    at In.request (/opt/lavamusic/node_modules/@prisma/client/runtime/library.js:122:5919)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async l (/opt/lavamusic/node_modules/@prisma/client/runtime/library.js:127:11167)
    at async ServerData.get_247 (file:///opt/lavamusic/dist/database/server.js:82:20)
    at async NodeConnect.run (file:///opt/lavamusic/dist/events/player/NodeConnect.js:11:20) {
  clientVersion: '5.14.0',
  errorCode: undefined
}

**Comment by LucasB25** [comment]
try now https://github.com/appujet/lavamusic/blob/main/Dockerfile

**Comment by elBelgg** [comment]
Both main and latest keeps giving me that error (im using docker compose in Unraid)

**Comment by appujet** [comment]
fixed mabye ba5bb09e00bba77f9d9e41513a2617f5173164f4
