### ISSUE TITLE
DiscordAPIError[0]: 404: Not Found 

### ISSUE THREAD

**Issue by DlgshKurd** [appujet/lavamusic#633]
[7/21/2024] [1:05:44 AM] [NodeConnect.js] [Lavamusic] › ✔  success   Node Lavamusic is ready!
[7/21/2024] [1:05:44 AM] [index.js] [Lavamusic] › ▶  start     [CLIENT] Shard 0 connected to Discord's Gateway.
[7/21/2024] [1:05:44 AM] [index.js] [Lavamusic] › ▶  start     [CLIENT] 1 shard(s) spawned.
[7/21/2024] [1:05:44 AM] [Lavamusic.js] [Lavamusic] › ✖  error     DiscordAPIError[0]: 404: Not Found 
    at handleErrors (/home/kurd/NEWWWWWW/lavamusic/node_modules/@discordjs/rest/dist/index.js:730:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SequentialHandler.runRequest (/home/kurd/NEWWWWWW/lavamusic/node_modules/@discordjs/rest/dist/index.js:1133:23)
    at async SequentialHandler.queueRequest (/home/kurd/NEWWWWWW/lavamusic/node_modules/@discordjs/rest/dist/index.js:963:14)
    at async _REST.request (/home/kurd/NEWWWWWW/lavamusic/node_modules/@discordjs/rest/dist/index.js:1278:22)
    at async Lavamusic.<anonymous> (file:///home/kurd/NEWWWWWW/lavamusic/dist/structures/Lavamusic.js:112:17)

**Comment by DlgshKurd** [comment]
just set PRODUCTION to true in .env file, and it should solve this issue.
