### ISSUE TITLE
Already compiled the bot, still giving errors

### ISSUE THREAD

**Issue by scattyypie** [appujet/lavamusic#634]
node:fs:1400
  handleErrorFromBinding(ctx);
  ^
Error: ENOENT: no such file or directory, mkdir '/home/container/languages/locales'
    at Object.mkdirSync (node:fs:1400:3)
    at write (/home/container/node_modules/i18n/i18n.js:1286:12)
    at read (/home/container/node_modules/i18n/i18n.js:1265:7)
    at Array.forEach (<anonymous>)
    at Object.i18nConfigure [as configure] (/home/container/node_modules/i18n/i18n.js:220:21)
    at initI18n (file:///home/container/dist/structures/I18n.js:7:10)
    at Lavamusic.start (file:///home/container/dist/structures/Lavamusic.js:30:9)
    at file:///home/container/dist/LavaClient.js:10:8
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25) {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/home/container/languages/locales'
}
Node.js v19.9.0
[7/22/2024] [3:57:35 PM] [index.js] [Lavamusic] › ✖  error     [CLIENT] An error has occurred: Error [ShardingReadyDied]: Shard 0's process exited before its Client became ready.
    at Shard.onDeath (/home/container/node_modules/discord.js/src/sharding/Shard.js:178:16)
    at Object.onceWrapper (node:events:628:26)
    at Shard.emit (node:events:513:28)
    at Shard._handleExit (/home/container/node_modules/discord.js/src/sharding/Shard.js:439:10)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess._handle.onexit (node:internal/child_process:293:12) {
  code: 'ShardingReadyDied'
}
node:fs:1400
  handleErrorFromBinding(ctx);
  ^
Error: ENOENT: no such file or directory, mkdir '/home/container/languages/locales'
    at Object.mkdirSync (node:fs:1400:3)
    at write (/home/container/node_modules/i18n/i18n.js:1286:12)
    at read (/home/container/node_modules/i18n/i18n.js:1265:7)
    at Array.forEach (<anonymous>)
    at Object.i18nConfigure [as configure] (/home/container/node_modules/i18n/i18n.js:220:21)
    at initI18n (file:///home/container/dist/structures/I18n.js:7:10)
    at Lavamusic.start (file:///home/container/dist/structures/Lavamusic.js:30:9)
    at file:///home/container/dist/LavaClient.js:10:8
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25) {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/home/container/languages/locales'
}
Node.js v19.9.0
/home/container/node_modules/discord.js/src/sharding/Shard.js:178
        reject(new DiscordjsError(ErrorCodes.ShardingReadyDied, this.id));
               ^
Error [ShardingReadyDied]: Shard 0's process exited before its Client became ready.
    at Shard.onDeath (/home/container/node_modules/discord.js/src/sharding/Shard.js:178:16)
    at Object.onceWrapper (node:events:628:26)
    at Shard.emit (node:events:513:28)
    at Shard._handleExit (/home/container/node_modules/discord.js/src/sharding/Shard.js:439:10)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess._handle.onexit (node:internal/child_process:293:12)
Emitted 'error' event on Shard instance at:
    at /home/container/node_modules/discord.js/src/sharding/Shard.js:447:56
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ShardingReadyDied'
}
Node.js v19.9.0

**Comment by infnibor** [comment]
> node:fs:1400 handleErrorFromBinding(ctx); ^ Error: ENOENT: no such file or directory, mkdir '/home/container/languages/locales' at Object.mkdirSync (node:fs:1400:3) at write (/home/container/node_modules/i18n/i18n.js:1286:12) at read (/home/container/node_modules/i18n/i18n.js:1265:7) at Array.forEach () at Object.i18nConfigure [as configure] (/home/container/node_modules/i18n/i18n.js:220:21) at initI18n (file:///home/container/dist/structures/I18n.js:7:10) at Lavamusic.start (file:///home/container/dist/structures/Lavamusic.js:30:9) at file:///home/container/dist/LavaClient.js:10:8 at ModuleJob.run (node:internal/modules/esm/module_job:193:25) { errno: -2, syscall: 'mkdir', code: 'ENOENT', path: '/home/container/languages/locales' } Node.js v19.9.0 [7/22/2024] [3:57:35 PM] [index.js] [Lavamusic] › ✖ error [CLIENT] An error has occurred: Error [ShardingReadyDied]: Shard 0's process exited before its Client became ready. at Shard.onDeath (/home/container/node_modules/discord.js/src/sharding/Shard.js:178:16) at Object.onceWrapper (node:events:628:26) at Shard.emit (node:events:513:28) at Shard._handleExit (/home/container/node_modules/discord.js/src/sharding/Shard.js:439:10) at ChildProcess.emit (node:events:513:28) at ChildProcess._handle.onexit (node:internal/child_process:293:12) { code: 'ShardingReadyDied' } node:fs:1400 handleErrorFromBinding(ctx); ^ Error: ENOENT: no such file or directory, mkdir '/home/container/languages/locales' at Object.mkdirSync (node:fs:1400:3) at write (/home/container/node_modules/i18n/i18n.js:1286:12) at read (/home/container/node_modules/i18n/i18n.js:1265:7) at Array.forEach () at Object.i18nConfigure [as configure] (/home/container/node_modules/i18n/i18n.js:220:21) at initI18n (file:///home/container/dist/structures/I18n.js:7:10) at Lavamusic.start (file:///home/container/dist/structures/Lavamusic.js:30:9) at file:///home/container/dist/LavaClient.js:10:8 at ModuleJob.run (node:internal/modules/esm/module_job:193:25) { errno: -2, syscall: 'mkdir', code: 'ENOENT', path: '/home/container/languages/locales' } Node.js v19.9.0 /home/container/node_modules/discord.js/src/sharding/Shard.js:178 reject(new DiscordjsError(ErrorCodes.ShardingReadyDied, this.id)); ^ Error [ShardingReadyDied]: Shard 0's process exited before its Client became ready. at Shard.onDeath (/home/container/node_modules/discord.js/src/sharding/Shard.js:178:16) at Object.onceWrapper (node:events:628:26) at Shard.emit (node:events:513:28) at Shard._handleExit (/home/container/node_modules/discord.js/src/sharding/Shard.js:439:10) at ChildProcess.emit (node:events:513:28) at ChildProcess._handle.onexit (node:internal/child_process:293:12) Emitted 'error' event on Shard instance at: at /home/container/node_modules/discord.js/src/sharding/Shard.js:447:56 at process.processTicksAndRejections (node:internal/process/task_queues:95:5) { code: 'ShardingReadyDied' } Node.js v19.9.0

You are missing a translation folder which is added as a submodule to the repository

**Comment by scattyypie** [comment]
so do i create it myself?

**Comment by infnibor** [comment]
> so do i create it myself?

You should have a languages ​​folder and in it a locales folder and in it the files that are in the link below
https://github.com/appujet/languages/tree/main/locales
