### ISSUE TITLE
Docker error v4.6.6

### ISSUE THREAD

**Issue by elBelgg** [appujet/lavamusic#646]
Using the latest version of LavaMusic with Docker gives me this error:

```
[7/28/2024] [8:06:59 PM] [index.js] [Lavamusic] › ✖  error     [CLIENT] An error has occurred: Error [ShardingReadyDied]: Shard 0's process exited before its Client became ready.
    at Shard.onDeath (/opt/lavamusic/node_modules/discord.js/src/sharding/Shard.js:178:16)
    at Object.onceWrapper (node:events:635:26)
    at Shard.emit (node:events:520:28)
    at Shard._handleExit (/opt/lavamusic/node_modules/discord.js/src/sharding/Shard.js:439:10)
    at ChildProcess.emit (node:events:520:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12) {
  code: 'ShardingReadyDied'
}
```

It doesnt happen in v4.3.3

**Comment by elBelgg** [comment]
Using main fixes it
