### ISSUE TITLE
Error on main tag in docker

### ISSUE THREAD

**Issue by Bitnik212** [appujet/lavamusic#650]
Bot running by docker

My env:

```bash
# Your lavalink url
LAVALINK_URL: $LAVALINK_URL
# Your lavalink password
LAVALINK_AUTH: $LAVALINK_AUTH
# Your lavalink name
LAVALINK_NAME: $LAVALINK_NAME
# Your lavalink secure (true or false)
LAVALINK_SECURE: "true"
PRODUCTION: "true"
PREFIX: "/"
GUILD_ID: "DELETED"
OWNER_IDS: "DELETED"
TOKEN: $TOKEN # Your bot token.
CLIENT_ID: $CLIENT_ID # Your bot's client ID (If this value is left blank, bots cannot be invited using /invite or /about commands.).
BOT_STATUS: "online" # Your bot status (online, dnd, idle, invisible or offline).
BOT_ACTIVITY_TYPE: 0 # Activity type is a number from 0 to 5. See more here: https://discord.com/developers/docs/topics/gateway-events#activity-object-activity-types
BOT_ACTIVITY: "Lavamusic" # Your bot activity.
AUTO_NODE: "false" # true for auto node. It is given from lavainfo-api (https://lavainfo-api.deno.dev)."localhost:2333" # Your Lavalink url (If auto node is true, then you can leave it blank).
MAX_PLAYLIST_SIZE: "1000" # Max playlist size.
MAX_QUEUE_SIZE: "1000" # Max queue size.    
DATABASE_URL: "postgresql://lavamusic:lavamusic@postgres:5432/lavamusic"
```

Got this error on send message "/play" to bot in discord:

```
[7/31/2024] [10:27:46 AM] [InteractionCreate.js] [Lavamusic] › ✖  error     TypeError: Cannot set properties of undefined (setting 'locale') 
    at Object.i18nSetLocale [as setLocale] (/opt/lavamusic/node_modules/i18n/i18n.js:492:25)
    at T (file:///opt/lavamusic/dist/structures/I18n.js:28:10)
    at Context.locale (file:///opt/lavamusic/dist/structures/Context.js:78:16)
    at Play.run (file:///opt/lavamusic/dist/commands/music/Play.js:47:40)
    at InteractionCreate.run (file:///opt/lavamusic/dist/events/client/InteractionCreate.js:168:31)
[7/31/2024] [10:27:46 AM] [antiCrash.js] [Lavamusic] › ✖  error     Uncaught Exception thrown: TypeError: Cannot set properties of undefined (setting 'locale')
    at Object.i18nSetLocale [as setLocale] (/opt/lavamusic/node_modules/i18n/i18n.js:492:25)
    at T (file:///opt/lavamusic/dist/structures/I18n.js:28:10)
    at InteractionCreate.run (file:///opt/lavamusic/dist/events/client/InteractionCreate.js:189:30)
```

**Comment by Bitnik212** [comment]
Resolve by mount https://github.com/appujet/lavamusic/tree/main/locales to /opt/lavamusic/languages/locales
