### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Parthsonare** [appujet/lavamusic#679]
DiscordAPIError[50035]: Invalid Form Body
data.choices[0].name[BASE_TYPE_BAD_LENGTH]: Must be between 1 and 100 in length.
    at handleErrors (/home/container/node_modules/@discordjs/rest/dist/index.js:730:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BurstHandler.runRequest (/home/container/node_modules/@discordjs/rest/dist/index.js:835:23)
    at async _REST.request (/home/container/node_modules/@discordjs/rest/dist/index.js:1278:22)
    at async AutocompleteInteraction.respond (/home/container/node_modules/discord.js/src/structures/AutocompleteInteraction.js:86:5)
    at async Play.autocomplete (file:///home/container/dist/commands/music/Play.js:308:9)
    at async InteractionCreate.run (file:///home/container/dist/events/client/InteractionCreate.js:170:17) {
  requestBody: { files: undefined, json: { type: 8, data: [Object] } },
  rawError: {
    message: 'Invalid Form Body',
    code: 50035,
    errors: { data: [Object] }
  },
  code: 50035,
  status: 400,
  method: 'POST',
  url: 'https://discord.com/api/v10/interactions/1272398886815793265/aW50ZXJhY3Rpb246MTI3MjM5ODg4NjgxNTc5MzI2NTprWU9UazRzeDJpb29hQnY2NHFNam8zQXdGN0RLZ1UwT0d0aUJYMldEZXFCRFNDb2FMNmNidnlQRzQ5cllDdTRyNDJidGJ6dG9qaFdkdXJtQ2p3ZW0yNUtnZEZHb1VhM1RtQVdPWEc4NFJPVXdpOEU3MVRadW54eXdkT2tZR2JWaA/callback'
}

AND

Error in 247 command: DiscordAPIError[10062]: Unknown interaction
    at handleErrors (/home/container/node_modules/@discordjs/rest/dist/index.js:730:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BurstHandler.runRequest (/home/container/node_modules/@discordjs/rest/dist/index.js:835:23)
    at async _REST.request (/home/container/node_modules/@discordjs/rest/dist/index.js:1278:22)
    at async ChatInputCommandInteraction.reply (/home/container/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:114:5)
    at async Context.sendMessage (file:///home/container/dist/structures/Context.js:43:28)
    at async _247.run (file:///home/container/dist/commands/config/247.js:59:20)
    at async InteractionCreate.run (file:///home/container/dist/events/client/InteractionCreate.js:156:17) {
  requestBody: { files: [], json: { type: 4, data: [Object] } },
  rawError: { message: 'Unknown interaction', code: 10062 },
  code: 10062,
  status: 404,
  method: 'POST',
  url: 'https://discord.com/api/v10/interactions/1272415741676752938/aW50ZXJhY3Rpb246MTI3MjQxNTc0MTY3Njc1MjkzODo2SGlSYk91UEtnWDNXZmN6eFNFUDRrV2xaY0JxU2dxODA1dEhDVlBMZFdzOWdsdzVycXo0dFUwQ3BSRWZDSERaQms5MUU0T2ZxcmdFZVNFb3pUVDhadUx3TEF2bUZQVExSbGVhdUlCZXJMZGdkamFEeEFXM25zOHQ0ckVyNFZDMw/callback'
}

AND

[8/12/2024] [4:45:56 AM] [antiCrash.js] [Jazzmusic] › ✖  error     An unexpected error occurred: DiscordAPIError[10062]: Unknown interaction
    at handleErrors (/home/container/node_modules/@discordjs/rest/dist/index.js:730:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BurstHandler.runRequest (/home/container/node_modules/@discordjs/rest/dist/index.js:835:23)
    at async _REST.request (/home/container/node_modules/@discordjs/rest/dist/index.js:1278:22)
    at async ChatInputCommandInteraction.reply (/home/container/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:114:5)
    at async InteractionCreate.run (file:///home/container/dist/events/client/InteractionCreate.js:160:17) {
  requestBody: { files: [], json: { type: 4, data: [Object] } },
  rawError: { message: 'Unknown interaction', code: 10062 },
  code: 10062,
  status: 404,
  method: 'POST',
  url: 'https://discord.com/api/v10/interactions/1272415741676752938/aW50ZXJhY3Rpb246MTI3MjQxNTc0MTY3Njc1MjkzODo2SGlSYk91UEtnWDNXZmN6eFNFUDRrV2xaY0JxU2dxODA1dEhDVlBMZFdzOWdsdzVycXo0dFUwQ3BSRWZDSERaQms5MUU0T2ZxcmdFZVNFb3pUVDhadUx3TEF2bUZQVExSbGVhdUlCZXJMZGdkamFEeEFXM25zOHQ0ckVyNFZDMw/callback'
}

**Comment by infnibor** [comment]
> DiscordAPIError[50035]: Invalid Form Body data.choices[0].name[BASE_TYPE_BAD_LENGTH]: Must be between 1 and 100 in length. at handleErrors (/home/container/node_modules/@discordjs/rest/dist/index.js:730:13) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async BurstHandler.runRequest (/home/container/node_modules/@discordjs/rest/dist/index.js:835:23) at async _REST.request (/home/container/node_modules/@discordjs/rest/dist/index.js:1278:22) at async AutocompleteInteraction.respond (/home/container/node_modules/discord.js/src/structures/AutocompleteInteraction.js:86:5) at async Play.autocomplete (file:///home/container/dist/commands/music/Play.js:308:9) at async InteractionCreate.run (file:///home/container/dist/events/client/InteractionCreate.js:170:17) { requestBody: { files: undefined, json: { type: 8, data: [Object] } }, rawError: { message: 'Invalid Form Body', code: 50035, errors: { data: [Object] } }, code: 50035, status: 400, method: 'POST', url: 'https://discord.com/api/v10/interactions/1272398886815793265/aW50ZXJhY3Rpb246MTI3MjM5ODg4NjgxNTc5MzI2NTprWU9UazRzeDJpb29hQnY2NHFNam8zQXdGN0RLZ1UwT0d0aUJYMldEZXFCRFNDb2FMNmNidnlQRzQ5cllDdTRyNDJidGJ6dG9qaFdkdXJtQ2p3ZW0yNUtnZEZHb1VhM1RtQVdPWEc4NFJPVXdpOEU3MVRadW54eXdkT2tZR2JWaA/callback' }
> 
> AND
> 
> Error in 247 command: DiscordAPIError[10062]: Unknown interaction at handleErrors (/home/container/node_modules/@discordjs/rest/dist/index.js:730:13) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async BurstHandler.runRequest (/home/container/node_modules/@discordjs/rest/dist/index.js:835:23) at async _REST.request (/home/container/node_modules/@discordjs/rest/dist/index.js:1278:22) at async ChatInputCommandInteraction.reply (/home/container/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:114:5) at async Context.sendMessage (file:///home/container/dist/structures/Context.js:43:28) at async _247.run (file:///home/container/dist/commands/config/247.js:59:20) at async InteractionCreate.run (file:///home/container/dist/events/client/InteractionCreate.js:156:17) { requestBody: { files: [], json: { type: 4, data: [Object] } }, rawError: { message: 'Unknown interaction', code: 10062 }, code: 10062, status: 404, method: 'POST', url: 'https://discord.com/api/v10/interactions/1272415741676752938/aW50ZXJhY3Rpb246MTI3MjQxNTc0MTY3Njc1MjkzODo2SGlSYk91UEtnWDNXZmN6eFNFUDRrV2xaY0JxU2dxODA1dEhDVlBMZFdzOWdsdzVycXo0dFUwQ3BSRWZDSERaQms5MUU0T2ZxcmdFZVNFb3pUVDhadUx3TEF2bUZQVExSbGVhdUlCZXJMZGdkamFEeEFXM25zOHQ0ckVyNFZDMw/callback' }
> 
> AND
> 
> [8/12/2024] [4:45:56 AM] [antiCrash.js] [Jazzmusic] › ✖ error An unexpected error occurred: DiscordAPIError[10062]: Unknown interaction at handleErrors (/home/container/node_modules/@discordjs/rest/dist/index.js:730:13) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async BurstHandler.runRequest (/home/container/node_modules/@discordjs/rest/dist/index.js:835:23) at async _REST.request (/home/container/node_modules/@discordjs/rest/dist/index.js:1278:22) at async ChatInputCommandInteraction.reply (/home/container/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:114:5) at async InteractionCreate.run (file:///home/container/dist/events/client/InteractionCreate.js:160:17) { requestBody: { files: [], json: { type: 4, data: [Object] } }, rawError: { message: 'Unknown interaction', code: 10062 }, code: 10062, status: 404, method: 'POST', url: 'https://discord.com/api/v10/interactions/1272415741676752938/aW50ZXJhY3Rpb246MTI3MjQxNTc0MTY3Njc1MjkzODo2SGlSYk91UEtnWDNXZmN6eFNFUDRrV2xaY0JxU2dxODA1dEhDVlBMZFdzOWdsdzVycXo0dFUwQ3BSRWZDSERaQms5MUU0T2ZxcmdFZVNFb3pUVDhadUx3TEF2bUZQVExSbGVhdUlCZXJMZGdkamFEeEFXM25zOHQ0ckVyNFZDMw/callback' }

If there is an error 1 invalid from body in the play command, update the code because it was fixed
