### ISSUE TITLE
[Bug]: Searching doesn't work within voice channel chat

### ISSUE THREAD

**Issue by Kickbub** [appujet/lavamusic#769]
### Bug description

When you use the voice channel chat channel, /play search function does not return anything.

### Steps to reproduce

Connect to a voice channel.
Use the voice channel chat.
Try to use the /play command to search.

### Operating System

Ubuntu 22.04.5 LTS

### Node.js version

23.3.0

### java version

18.0.2.1

### Application/Library version

c13d88d

### Error logs or screenshots

```
[12/15/2024] [8:46:34 PM] [InteractionCreate.js] [Lavamusic] › ✖  error     TypeError: Cannot read properties of undefined (reading 'search')
    at LavalinkClient.search (/opt/lavamusic/dist/structures/LavalinkClient.js:31:35)
    at Play.autocomplete (/opt/lavamusic/dist/commands/music/Play.js:100:47)
    at InteractionCreate.run (/opt/lavamusic/dist/events/client/InteractionCreate.js:210:31)
    at Lavamusic.<anonymous> (/opt/lavamusic/dist/structures/Lavamusic.js:176:60)
    at Lavamusic.emit (node:events:525:35)
    at InteractionCreateAction.handle (/opt/lavamusic/node_modules/discord.js/src/client/actions/InteractionCreate.js:97:12)
    at module.exports [as INTERACTION_CREATE] (/opt/lavamusic/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)
    at WebSocketManager.handlePacket (/opt/lavamusic/node_modules/discord.js/src/client/websocket/WebSocketManager.js:348:31)
    at WebSocketManager.<anonymous> (/opt/lavamusic/node_modules/discord.js/src/client/websocket/WebSocketManager.js:232:12)
    at WebSocketManager.emit (/opt/lavamusic/node_modules/@vladfrangu/async_event_emitter/dist/index.cjs:287:31)
```

**Comment by Kickbub** [comment]
Ensure lavalink starts before lavamusic attempts to connect to the node.
