### ISSUE TITLE
[Bug]: Prisma cannot find the required `libssl` system library in your system. Please install openssl-1.1.x and try again.

### ISSUE THREAD

**Issue by vitakee** [appujet/lavamusic#773]
### Bug description

```
    █░░ ▄▀█ █░█ ▄▀█ █▀▄▀█ █░█ █▀ █ █▀▀
    █▄▄ █▀█ ▀▄▀ █▀█ █░▀░█ █▄█ ▄█ █ █▄▄

             .:::.=++=:.:-:             
            =##############*            
            *###############.           
             =++=*####*=++=:            
                 .*##*:                               
               .+######*:               
              =*#########+.             
            :*############*-            
           =################*.          
         :*##################*=         
       .+######################*:       
       *#########################.      
       .::::::::::::::::::::::::.       


[12/24/2024] [4:44:55 PM] [I18n.js] [Lavamusic] › ℹ  info      I18n has been initialized
[12/24/2024] [4:44:55 PM] [Lavamusic.js] [Lavamusic] › ⚠  warn      Top.gg token not found!
[12/24/2024] [4:44:55 PM] [Lavamusic.js] [Lavamusic] › ℹ  info      Successfully loaded commands!
[12/24/2024] [4:44:55 PM] [Lavamusic.js] [Lavamusic] › ℹ  info      Successfully loaded events!
[12/24/2024] [4:44:55 PM] [index.js] [Lavamusic] › ℹ  info      Loaded plugin: AntiCrash Plugin v1.0.0
[12/24/2024] [4:44:55 PM] [index.js] [Lavamusic] › ℹ  info      Loaded plugin: KeepAlive Plugin v1.0.0
[12/24/2024] [4:44:55 PM] [index.js] [Lavamusic] › ℹ  info      Loaded plugin: Update Status Plugin v1.0.0
[12/24/2024] [4:44:55 PM] [keepAlive.js] [Lavamusic] › ℹ  info      Keep-Alive server is running on port 3000
[12/24/2024] [4:44:56 PM] [antiCrash.js] [Lavamusic] › ✖  error     Unhandled Rejection at: Promise {
  <rejected> PrismaClientInitializationError: Unable to require(`/home/runner/lavamusic/node_modules/.prisma/client/libquery_engine-debian-openssl-1.1.x.so.node`).
  Prisma cannot find the required `libssl` system library in your system. Please install openssl-1.1.x and try again.
  
  Details: libssl.so.1.1: cannot open shared object file: No such file or directory
      at Object.loadLibrary (/home/runner/lavamusic/node_modules/@prisma/client/runtime/library.js:111:9152)
      at async _r.loadEngine (/home/runner/lavamusic/node_modules/@prisma/client/runtime/library.js:112:448)
      at async _r.instantiateLibrary (/home/runner/lavamusic/node_modules/@prisma/client/runtime/library.js:111:12366) {
    clientVersion: '6.1.0',
    errorCode: undefined
  }
} reason: PrismaClientInitializationError: Unable to require(`/home/runner/lavamusic/node_modules/.prisma/client/libquery_engine-debian-openssl-1.1.x.so.node`).
Prisma cannot find the required `libssl` system library in your system. Please install openssl-1.1.x and try again.

Details: libssl.so.1.1: cannot open shared object file: No such file or directory
    at Object.loadLibrary (/home/runner/lavamusic/node_modules/@prisma/client/runtime/library.js:111:9152)
    at async _r.loadEngine (/home/runner/lavamusic/node_modules/@prisma/client/runtime/library.js:112:448)
    at async _r.instantiateLibrary (/home/runner/lavamusic/node_modules/@prisma/client/runtime/library.js:111:12366) {
  clientVersion: '6.1.0',
  errorCode: undefined
}
[12/24/2024] [4:44:56 PM] [Ready.js] [Lavamusic] › ✔  success   ayase-chan#8046 is ready!
[12/24/2024] [4:44:56 PM] [Ready.js] [Lavamusic] › ⚠  warn      Top.gg token not found. Skipping auto poster.
[12/24/2024] [4:44:57 PM] [antiCrash.js] [Lavamusic] › ✖  error     Uncaught Exception thrown: Error [ERR_UNHANDLED_ERROR]: Unhandled error. (<ref *2> LavalinkNode {
  heartBeatPingTimestamp: 0,
  heartBeatPongTimestamp: 0,
  heartBeatInterval: undefined,
  pingTimeout: undefined,
  isAlive: false,
  options: {
    secure: false,
    retryAmount: 5,
    retryDelay: 60000,
    requestSignalTimeoutMS: 10000,
    heartBeatInterval: 30000,
    closeOnError: true,
    enablePingOnStatsCheck: true,
    id: 'Local Node',
    host: 'localhost',
    port: 2333,
    authorization: 'youshallnotpass',
    regions: []
  },
  calls: 0,
  stats: {
    players: 0,
    playingPlayers: 0,
    cpu: { cores: 0, lavalinkLoad: 0, systemLoad: 0 },
    memory: { allocated: 0, free: 0, reservable: 0, used: 0 },
    uptime: 0,
    frameStats: { deficit: 0, nulled: 0, sent: 0 }
  },
  sessionId: null,
  resuming: { enabled: true, timeout: null },
  info: null,
  NodeManager: <ref *1> NodeManager {
    _events: [Object: null prototype] {
      connect: [Function (anonymous)],
      destroy: [Function (anonymous)]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    LavalinkManager: LavalinkClient {
      _events: [Object: null prototype],
      _eventsCount: 5,
      _maxListeners: undefined,
      options: [Object],
      nodeManager: [Circular *1],
      utils: [ManagerUtils],
      initiated: true,
      players: MiniMap(0) [Map] {},
      client: [Lavamusic],
      [Symbol(shapeMode)]: false,
      [Symbol(kCapture)]: false
    },
    nodes: MiniMap(1) [Map] { 'Local Node' => [Circular *2] },
    [Symbol(shapeMode)]: false,
    [Symbol(kCapture)]: false
  },
  reconnectTimeout: undefined,
  reconnectAttempts: 1,
  socket: WebSocket {
    _events: [Object: null prototype] {
      open: [Function: bound open] AsyncFunction,
      close: [Function (anonymous)],
      message: [Function: bound message] AsyncFunction,
      error: [Function: bound error]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    _binaryType: 'nodebuffer',
    _closeCode: 1006,
    _closeFrameReceived: false,
    _closeFrameSent: false,
    _closeMessage: <Buffer >,
    _closeTimer: null,
    _errorEmitted: true,
    _extensions: {},
    _paused: false,
    _protocol: '',
    _readyState: 2,
    _receiver: null,
    _sender: null,
    _socket: null,
    _bufferedAmount: 0,
    _isServer: false,
    _redirects: 0,
    _autoPong: true,
    _url: 'ws://localhost:2333/v4/websocket',
    _req: null,
    [Symbol(shapeMode)]: false,
    [Symbol(kCapture)]: false
  },
  version: 'v4',
  decode: {
    singleTrack: [AsyncFunction: singleTrack],
    multipleTracks: [AsyncFunction: multipleTracks]
  },
  lyrics: {
    get: [AsyncFunction: get],
    getCurrent: [AsyncFunction: getCurrent],
    subscribe: [AsyncFunction: subscribe],
    unsubscribe: [AsyncFunction: unsubscribe]
  },
  routePlannerApi: {
    getStatus: [AsyncFunction: getStatus],
    unmarkFailedAddress: [AsyncFunction: unmarkFailedAddress],
    unmarkAllFailedAddresses: [AsyncFunction: unmarkAllFailedAddresses]
  }
})
    at NodeManager.emit (node:events:507:17)
    at NodeManager.emit (/home/runner/lavamusic/node_modules/lavalink-client/dist/cjs/structures/NodeManager.js:16:22)
    at LavalinkNode.error (/home/runner/lavamusic/node_modules/lavalink-client/dist/cjs/structures/Node.js:977:26)
    at WebSocket.emit (node:events:518:28)
    at emitErrorAndClose (/home/runner/lavamusic/node_modules/ws/lib/websocket.js:1041:13)
    at ClientRequest.<anonymous> (/home/runner/lavamusic/node_modules/ws/lib/websocket.js:881:5)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:101:11)
    at Socket.socketErrorListener (node:_http_client:504:5)
    at Socket.emit (node:events:518:28) {
  code: 'ERR_UNHANDLED_ERROR',
  context: LavalinkNode {
    heartBeatPingTimestamp: 0,
    heartBeatPongTimestamp: 0,
    heartBeatInterval: undefined,
    pingTimeout: undefined,
    isAlive: false,
    options: {
      secure: false,
      retryAmount: 5,
      retryDelay: 60000,
      requestSignalTimeoutMS: 10000,
      heartBeatInterval: 30000,
      closeOnError: true,
      enablePingOnStatsCheck: true,
      id: 'Local Node',
      host: 'localhost',
      port: 2333,
      authorization: 'youshallnotpass',
      regions: []
    },
    calls: 0,
    stats: {
      players: 0,
      playingPlayers: 0,
      cpu: [Object],
      memory: [Object],
      uptime: 0,
      frameStats: [Object]
    },
    sessionId: null,
    resuming: { enabled: true, timeout: null },
    info: null,
    NodeManager: NodeManager {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      LavalinkManager: [LavalinkClient],
      nodes: [MiniMap [Map]],
      [Symbol(shapeMode)]: false,
      [Symbol(kCapture)]: false
    },
    reconnectTimeout: undefined,
    reconnectAttempts: 1,
    socket: WebSocket {
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      _binaryType: 'nodebuffer',
      _closeCode: 1006,
      _closeFrameReceived: false,
      _closeFrameSent: false,
      _closeMessage: <Buffer >,
      _closeTimer: null,
      _errorEmitted: true,
      _extensions: {},
      _paused: false,
      _protocol: '',
      _readyState: 2,
      _receiver: null,
      _sender: null,
      _socket: null,
      _bufferedAmount: 0,
      _isServer: false,
      _redirects: 0,
      _autoPong: true,
      _url: 'ws://localhost:2333/v4/websocket',
      _req: null,
      [Symbol(shapeMode)]: false,
      [Symbol(kCapture)]: false
    },
    version: 'v4',
    decode: {
      singleTrack: [AsyncFunction: singleTrack],
      multipleTracks: [AsyncFunction: multipleTracks]
    },
    lyrics: {
      get: [AsyncFunction: get],
      getCurrent: [AsyncFunction: getCurrent],
      subscribe: [AsyncFunction: subscribe],
      unsubscribe: [AsyncFunction: unsubscribe]
    },
    routePlannerApi: {
      getStatus: [AsyncFunction: getStatus],
      unmarkFailedAddress: [AsyncFunction: unmarkFailedAddress],
      unmarkAllFailedAddresses: [AsyncFunction: unmarkAllFailedAddresses]
    }
  }
}
[12/24/2024] [4:44:57 PM] [shard.js] [Lavamusic] › ▶  start     [CLIENT] Shard 0 connected to Discord's Gateway.
[12/24/2024] [4:44:57 PM] [shard.js] [Lavamusic] › ▶  start     [CLIENT] 1 shard(s) spawned.
```

### Steps to reproduce

1. Import to Replit from Github
2. change .env
3. Run

### Operating System

Replit

### Node.js version

20

### Application/Library version

latest

**Comment by Dave187420** [comment]
I have the same issue i am using docker compose, it doesnt create a node "Error: No available Node was found, please add a LavalinkNode to the Manager via Manager"

**Comment by appujet** [comment]
fixed https://github.com/appujet/lavamusic/commit/d1363b70e6a06348c33743af3ab9e7cac4d8a9c2
